name: Export DAT to PDF

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc wkhtmltopdf
      - name: Convert to PDF
        run: pandoc DAT.md -o DAT.pdf --from markdown --to pdf --standalone --resource-path=.:images
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DAT-PDF
          path: DAT.pdf
